services:
  - type: web
    name: duhdecoder
    runtime: python
    plan: free
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt && python -m py_compile server.py
    startCommand: python server.py
